(function() {var implementors = {};
implementors["hyper"] = ["impl&lt;T, C&gt; <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for <a class="struct" href="https://docs.rs/tokio-core/0.1/tokio_core/io/frame/struct.Framed.html" title="struct tokio_core::io::frame::Framed">Framed</a>&lt;T, C&gt; <span class="where fmt-newline">where C: <a class="trait" href="https://docs.rs/tokio-core/0.1/tokio_core/io/frame/trait.Codec.html" title="trait tokio_core::io::frame::Codec">Codec</a>, T: <a class="trait" href="https://docs.rs/tokio-core/0.1/tokio_core/io/trait.Io.html" title="trait tokio_core::io::Io">Io</a></span>","impl <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for <a class="struct" href="https://docs.rs/tokio-core/0.1/tokio_core/net/tcp/struct.Incoming.html" title="struct tokio_core::net::tcp::Incoming">Incoming</a>","impl&lt;C&gt; <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for <a class="struct" href="https://docs.rs/tokio-core/0.1/tokio_core/net/udp/frame/struct.UdpFramed.html" title="struct tokio_core::net::udp::frame::UdpFramed">UdpFramed</a>&lt;C&gt; <span class="where fmt-newline">where C: <a class="trait" href="https://docs.rs/tokio-core/0.1/tokio_core/net/udp/frame/trait.UdpCodec.html" title="trait tokio_core::net::udp::frame::UdpCodec">UdpCodec</a></span>","impl <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for <a class="struct" href="https://docs.rs/tokio-core/0.1/tokio_core/reactor/interval/struct.Interval.html" title="struct tokio_core::reactor::interval::Interval">Interval</a>","impl&lt;T, E&gt; <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for Body&lt;T, E&gt;","impl <a class="trait" href="https://docs.rs/futures/0.1/futures/stream/trait.Stream.html" title="trait futures::stream::Stream">Stream</a> for <a class="struct" href="hyper/struct.Body.html" title="struct hyper::Body">Body</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
