(function() {var implementors = {};
implementors["hyper"] = ["impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='hyper/client/struct.Config.html' title='hyper::client::Config'>Config</a>&lt;<a class='struct' href='hyper/client/struct.UseDefaultConnector.html' title='hyper::client::UseDefaultConnector'>UseDefaultConnector</a>, <a class='struct' href='hyper/struct.Body.html' title='hyper::Body'>Body</a>&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='hyper/enum.Method.html' title='hyper::Method'>Method</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='hyper/header/struct.LanguageTag.html' title='hyper::header::LanguageTag'>LanguageTag</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='hyper/header/struct.Headers.html' title='hyper::header::Headers'>Headers</a>","impl&lt;B&gt; <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='hyper/server/struct.Response.html' title='hyper::server::Response'>Response</a>&lt;B&gt;","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='hyper/status/enum.StatusCode.html' title='hyper::status::StatusCode'>StatusCode</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='struct' href='hyper/struct.Uri.html' title='hyper::Uri'>Uri</a>","impl <a class='trait' href='https://doc.rust-lang.org/nightly/core/default/trait.Default.html' title='core::default::Default'>Default</a> for <a class='enum' href='hyper/enum.HttpVersion.html' title='hyper::HttpVersion'>HttpVersion</a>",];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
