(function() {var implementors = {};
implementors["hyper"] = [{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/client/conn/struct.Builder.html\" title=\"struct hyper::client::conn::Builder\">Builder</a>",synthetic:false,types:["hyper::client::conn::Builder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/client/struct.HttpConnector.html\" title=\"struct hyper::client::HttpConnector\">HttpConnector</a>",synthetic:false,types:["hyper::client::connect::http::HttpConnector"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/client/connect/struct.Destination.html\" title=\"struct hyper::client::connect::Destination\">Destination</a>",synthetic:false,types:["hyper::client::connect::Destination"]},{text:"impl&lt;C, B&gt; <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/client/struct.Client.html\" title=\"struct hyper::client::Client\">Client</a>&lt;C, B&gt;",synthetic:false,types:["hyper::client::Client"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/client/struct.Builder.html\" title=\"struct hyper::client::Builder\">Builder</a>",synthetic:false,types:["hyper::client::Builder"]},{text:"impl <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/clone/trait.Clone.html\" title=\"trait core::clone::Clone\">Clone</a> for <a class=\"struct\" href=\"hyper/server/conn/struct.Http.html\" title=\"struct hyper::server::conn::Http\">Http</a>",synthetic:false,types:["hyper::server::conn::Http"]},];

            if (window.register_implementors) {
                window.register_implementors(implementors);
            } else {
                window.pending_implementors = implementors;
            }
        
})()
